# Config for this game installation.

# Name: mezz_config_gui.config.appearance
# Description: mezz_config_gui.config.appearance.description
[appearance]
	# Name: mezz_config_gui.config.appearance.guiMode
	# Description: mezz_config_gui.config.appearance.guiMode.description
	# Valid Values: [WINDOW, FULLSCREEN]
	# Default Value: WINDOW
	guiMode = WINDOW

	# Name: mezz_config_gui.config.appearance.enableWindowResizing
	# Description: mezz_config_gui.config.appearance.enableWindowResizing.description
	# Valid Values: [true, false]
	# Default Value: true
	enableWindowResizing = true

	# Name: mezz_config_gui.config.appearance.windowWidth
	# Description: mezz_config_gui.config.appearance.windowWidth.description
	# Valid Values: An integer in the range [320, 8192] (inclusive)
	# Default Value: 380
	windowWidth = 380

	# Name: mezz_config_gui.config.appearance.windowHeight
	# Description: mezz_config_gui.config.appearance.windowHeight.description
	# Valid Values: An integer in the range [230, 8192] (inclusive)
	# Default Value: 300
	windowHeight = 300

	# Name: mezz_config_gui.config.appearance.navigationWidth
	# Description: mezz_config_gui.config.appearance.navigationWidth.description
	# Valid Values: An integer in the range [80, 8192] (inclusive)
	# Default Value: 110
	navigationWidth = 110


# Name: mezz_config_gui.config.valueDisplay
# Description: mezz_config_gui.config.valueDisplay.description
[valueDisplay]
	# Name: mezz_config_gui.config.valueDisplay.rowDensity
	# Description: mezz_config_gui.config.valueDisplay.rowDensity.description
	# Valid Values: [COMFORTABLE, COMPACT]
	# Default Value: COMFORTABLE
	rowDensity = COMFORTABLE

	# Name: mezz_config_gui.config.valueDisplay.numberDisplayMode
	# Description: mezz_config_gui.config.valueDisplay.numberDisplayMode.description
	# Valid Values: [SLIDER, TEXT_AND_BUTTONS]
	# Default Value: SLIDER
	numberDisplayMode = SLIDER

	# Name: mezz_config_gui.config.valueDisplay.showRowStriping
	# Description: mezz_config_gui.config.valueDisplay.showRowStriping.description
	# Valid Values: [true, false]
	# Default Value: true
	showRowStriping = true


# Name: mezz_config_gui.config.navigation
# Description: mezz_config_gui.config.navigation.description
[navigation]
	# Name: mezz_config_gui.config.navigation.inlineSubsectionLimit
	# Description: mezz_config_gui.config.navigation.inlineSubsectionLimit.description
	# Valid Values: Any integer greater than or equal to 0
	# Default Value: 10
	inlineSubsectionLimit = 10

	# Name: mezz_config_gui.config.navigation.rememberLastCategory
	# Description: mezz_config_gui.config.navigation.rememberLastCategory.description
	# Valid Values: [true, false]
	# Default Value: true
	rememberLastCategory = true

	# Name: mezz_config_gui.config.navigation.searchDescriptions
	# Description: mezz_config_gui.config.navigation.searchDescriptions.description
	# Valid Values: [true, false]
	# Default Value: true
	searchDescriptions = true

	# Name: mezz_config_gui.config.navigation.focusSearchOnOpen
	# Description: mezz_config_gui.config.navigation.focusSearchOnOpen.description
	# Valid Values: [true, false]
	# Default Value: false
	focusSearchOnOpen = false

	# Name: mezz_config_gui.config.navigation.smoothScrolling
	# Description: mezz_config_gui.config.navigation.smoothScrolling.description
	# Valid Values: [true, false]
	# Default Value: true
	smoothScrolling = true

	# Name: mezz_config_gui.config.navigation.scrollSpeed
	# Description: mezz_config_gui.config.navigation.scrollSpeed.description
	# Valid Values: An integer in the range [1, 50] (inclusive)
	# Default Value: 10
	scrollSpeed = 10

	# Name: mezz_config_gui.config.navigation.dragAutoScrollSpeed
	# Description: mezz_config_gui.config.navigation.dragAutoScrollSpeed.description
	# Valid Values: An integer in the range [1, 50] (inclusive)
	# Default Value: 6
	dragAutoScrollSpeed = 6


# Name: mezz_config_gui.config.editing
# Description: mezz_config_gui.config.editing.description
[editing]
	# Name: mezz_config_gui.config.editing.confirmPendingChangesOnClose
	# Description: mezz_config_gui.config.editing.confirmPendingChangesOnClose.description
	# Valid Values: [true, false]
	# Default Value: true
	confirmPendingChangesOnClose = true

	# Name: mezz_config_gui.config.editing.enableDragReordering
	# Description: mezz_config_gui.config.editing.enableDragReordering.description
	# Valid Values: [true, false]
	# Default Value: true
	enableDragReordering = true


# Name: mezz_config_gui.config.modList
# Description: mezz_config_gui.config.modList.description
[modList]
	# Name: mezz_config_gui.config.modList.modOrder
	# Description: mezz_config_gui.config.modList.modOrder.description
	# Valid Values: A bracketed list containing values of:
	# Any string
	# List requirements:
	# A list containing values of:
	# Any string
	# Default Value: []
	modOrder = []

	# Name: mezz_config_gui.config.modList.hiddenMods
	# Description: mezz_config_gui.config.modList.hiddenMods.description
	# Valid Values: A bracketed list containing values of:
	# Any string
	# List requirements:
	# A list containing values of:
	# Any string
	# Default Value: []
	hiddenMods = []


# Name: mezz_config_gui.config.integrations
# Description: mezz_config_gui.config.integrations.description
[integrations]
	# Name: mezz_config_gui.config.integrations.showKeyMappings
	# Description: mezz_config_gui.config.integrations.showKeyMappings.description
	# Valid Values: [true, false]
	# Default Value: true
	showKeyMappings = true

	# Name: mezz_config_gui.config.integrations.showKeyConflictDetails
	# Description: mezz_config_gui.config.integrations.showKeyConflictDetails.description
	# Valid Values: [true, false]
	# Default Value: true
	showKeyConflictDetails = true

	# Name: mezz_config_gui.config.integrations.enableNativeConfigDiscovery
	# Description: mezz_config_gui.config.integrations.enableNativeConfigDiscovery.description
	# Valid Values: [true, false]
	# Default Value: true
	# Requires a game restart to take effect.
	enableNativeConfigDiscovery = true


# Name: mezz_config_gui.config.advanced
# Description: mezz_config_gui.config.advanced.description
[advanced]
	# Name: mezz_config_gui.config.advanced.showAdvancedValueDetails
	# Description: mezz_config_gui.config.advanced.showAdvancedValueDetails.description
	# Valid Values: [true, false]
	# Default Value: false
	showAdvancedValueDetails = false

	# Name: mezz_config_gui.config.advanced.discoveryLogging
	# Description: mezz_config_gui.config.advanced.discoveryLogging.description
	# Valid Values: [OFF, WARNINGS, VERBOSE]
	# Default Value: WARNINGS
	discoveryLogging = WARNINGS


